pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/

  docker:
    image: plugins/docker:latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jnummelin/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master

  kontena:
    image: kontena/cli
    commands:
      - SSL_IGNORE_ERRORS=true kontena stack upgrade todo
    when:
      branch: master

services:
  database:
    image: mongo:3.2
