build:
  image: ruby:2.3
  commands:
    - bundle install --path=bundler
    - rspec spec/
cache:
  mount:
    - bundler
compose:
  mongodb:
    image: mongo:3.2
publish:
  docker:
    username: $$DOCKER_HUB_USER
    password: $$DOCKER_HUB_PWD
    email: $$DOCKER_HUB_EMAIL
    repo: kontena/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master
notify:
  webhook:
    urls:
      - https://95.85.41.216/drone/todo-example-app/deploy
    header:
      Authorization: Bearer $$KONTENA_TOKEN
    content_type: application/json
    when:
      branch: master
    template: >
      {"force":true}
