pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jnummelin/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master

  kontena:
    image: jnummelin/kontena-cli
    commands:
      - kontena app deploy -f kontena-cluster.yml


services:
  database:
    image: mongo:3.2
