pipeline:
  test:
    image: ruby:2.3
    commands:
      - bundle install --path=bundler
      - rspec spec/
  docker:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    repo: jnummelin/todo-example
    tag: latest
    file: Dockerfile
    when:
      branch: master


  curl:
    image: ruby:2.3
    commands:
      ->echo "Using token: $$KONTENA_TOKEN"
      ->curl -k -X POST -d '{"force":true}' -H "Content-Type: application/json" -H "Authorization: Bearer $$KONTENA_TOKEN" https://95.85.41.216/v1/services/drone/todo-example-app/deploy

services:
  database:
    image: mongo:3.2
