version: '2'
services:
  app:
    image: jnummelin/todo-example:latest
    ports:
      - 80:9292
    extends:
      file: docker-compose.yml
      service: web
    environment:
      - MONGODB_URI=mongodb://${project}-mongodb.kontena.local/todo_production

  mongodb:
    image: mongo:3.2
    command: mongod --smallfiles
    stateful: true
